version: 2.1

jobs:
    unit-and-integration-tests:
        docker:
            - image: node:18.17.0-slim
        resource_class: large
        parallelism: 10
        steps:
            - checkout
            - restore_cache:
                  name: Restore pnpm Package Cache
                  keys:
                      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install pnpm package manager
                  command: |
                      corepack enable
                      corepack prepare pnpm@latest-8 --activate
                      pnpm config set store-dir .pnpm-store
            - run:
                  name: Install Dependencies
                  command: |
                      pnpm install
            - save_cache:
                  name: Save pnpm Package Cache
                  key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - .pnpm-store
            - run:
                  name: Run Unit & Integration Jest Tests
                  command: |
                      pnpm run test:ci

    ai-e2e-tests:
        docker:
            - image: node:18.17.0-slim
        resource_class: large
        parallelism: 10
        steps:
            - checkout
            - restore_cache:
                  name: Restore pnpm Package Cache
                  keys:
                      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install pnpm package manager
                  command: |
                      corepack enable
                      corepack prepare pnpm@latest-8 --activate
                      pnpm config set store-dir .pnpm-store
            - run:
                  name: Install Dependencies
                  command: |
                      pnpm install
            - save_cache:
                  name: Save pnpm Package Cache
                  key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - .pnpm-store
            - run:
                  name: Run AI E2E Tests
                  command: |
                      pnpm run ai-e2e-test:ci

workflows:
    version: 2
    all_tests:
        jobs:
            - unit-and-integration-tests
            - ai-e2e-tests
